### ISSUE TITLE
Cannot receive CAN message

### ISSUE THREAD

**Issue by LeonNg963** [tier4/ars408_driver#33]
Hi there,
I'm using Kvaser Leaf Light v2 to receive CAN msg and it's okay
![image](https://github.com/tier4/ars408_driver/assets/101226019/3d60ee70-c456-4377-a7a8-3cc95e56e21c)
But running "continental_ars408_socket_can.launch.xml" have an error.
![image](https://github.com/tier4/ars408_driver/assets/101226019/b3143b2c-c56c-4e1b-9684-e544ded38b93)
Then, I try to launch "socket_can_receiver.launch.py" and find the revived CAN msg have an error.
![image](https://github.com/tier4/ars408_driver/assets/101226019/5d3366ba-8f21-4d9c-9a55-a2fe85d2d75d)
Any help? Thank you.

OS: Ubuntu 22.04
ROS: humble

**Comment by joaoperoni** [comment]
I am having this same issue, did you fix this?
